### ISSUE TITLE
Change naming of APIs for state and fetching state

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably-labs/ably-chat-swift#73]
https://github.com/ably-labs/ably-chat-swift/pull/54#discussion_r1782660210

@umair-ably wasn’t a fan of:

- using `current` as a property to mean "the current state of this object", and would prefer it be named `state`
  - Note: the naming of `current` is used in the public API of the SDK, which matches the JS naming and also matches the naming used in the core SDKs, and personally whilst I think it could be clearer ("current" what?), I can also live with it
- the naming of the `RoomLifecycle` enum, which he thinks should be called `RoomState` or `RoomLifecycleState`
  - Again, this naming comes from JS
  - I agree with this suggsted change but would like to understand the motivation for the current name, ask @AndyTWF

See [comment](https://github.com/ably-labs/ably-chat-swift/issues/73#issuecomment-2385973335) for agreed outcome to resolve this issue. 

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5015) by [Unito](https://www.unito.io)

**Comment by AndyTWF** [comment]
> using current as a property to mean "the current state of this object", and would prefer it be named state

We went with current for parity with the core SDKs.

We specifically didn't choose `state` because `state` often implies a larger, internal state. `status` on the other hand implies a single value, e.g. "the status of your order: accepted, delivered". We felt in context, it worked well, e.g.:

```ts
  room.status.current
```

In this example it's quite clear that you're getting the current room status.

> the naming of the RoomLifecycle enum, which he thinks should be called RoomState or RoomLifecycleState

Initially we wanted to call these enums `RoomStatus` and `ConnectionStatus`, but JS's lack of namespaces and conflicting identifiers made it not possible.

We wanted to avoid the term `State` for reasons mentioned above.

If you feel there's a better name, then happy to discuss alternatives!

**Comment by vladvelici** [comment]
@AndyTWF I just had a look at our JS code. I think if we swap the names everything makes more sense.

| | Current | New  |
|--------|------|--|
|The enum of statuses | `RoomLifecycle` | `RoomStatus`
|The object you use to get the status or subscribe to changes | `RoomStatus` | `RoomLifecycle` |

**Comment by AndyTWF** [comment]
> Do we need to achieve parity with the core SDKs? or was this something that felt right but perhaps doesn't matter as long as we try to keep parity between the Chat SDKs?

It was a deliberate design decision - we're expecting the Chat SDK to be used in concert with the core SDK in many applications (people using PubSub for other aspects of their app). So we went for parity whenever there's overlapping concepts between the two so that that things are intuitive between SDKs.

We did deviate in one or two places where it was an obvious improvement, however (e.g. the subscribe behaviour).

**Comment by AndyTWF** [comment]
> I just had a look at our JS code. I think if we swap the names everything makes more sense.

That's definitely a possible!

**Comment by paddybyers** [comment]
In the core API we only use `current` when it's a state change event, and that's when there's also a `previous`. It's not used anywhere to represent the current state outside of that context. current what anyway? If it's current state, then the field should be `state`.

**Comment by AndyTWF** [comment]
> Can we confirm we're happy to make the following changes:
> 
> * `current` becomes `status` in the ably-chat-swift SDK
> * RoomLifecycle is renamed to RoomStatus
> * RoomStatus is renamed to RoomLifecycle

SGTM - for JS we'll swap the interface and enum names for consistency, as well as the `current -> status` change

**Comment by umair-ably** [comment]
Sweet, we'll do the same - thanks all! I've also added this to the divergence [log](https://ably.atlassian.net/wiki/spaces/CHA/pages/3307405320/SDK+Divergence+Decision+Log)

**Comment by lawrence-forooghian** [comment]
I imagine we want to make the same change for connection lifecycle, right? That is, call the enum `ConnectionStatus` and the object that emits this status `ConnectionLifecycle`.

**Comment by AndyTWF** [comment]
> That is, call the enum ConnectionStatus and the object that emits this status ConnectionLifecycle.

For this we already have `ConnectionStatus` as the enum. I somewhat prefer `Connection` as the interface name - I don't think `Lifecycle` on the end adds anything useful / distinguishes it from something else

**Comment by lawrence-forooghian** [comment]
> For this we already have `ConnectionStatus` as the enum.

Are you sure about that? From what I’m seeing, [`ConnectionStatus` is the interface that emits the enum](https://github.com/ably/ably-chat-js/blob/0ac639e8e3401400dcfe8228a1646e63a3415de5/src/core/connection-status.ts#L91) and [`ConnectionLifecycle` is the enum](https://github.com/ably/ably-chat-js/blob/0ac639e8e3401400dcfe8228a1646e63a3415de5/src/core/connection-status.ts#L14).

**Comment by AndyTWF** [comment]
> > For this we already have `ConnectionStatus` as the enum.
> 
> Are you sure about that? From what I’m seeing, [`ConnectionStatus` is the interface that emits the enum](https://github.com/ably/ably-chat-js/blob/0ac639e8e3401400dcfe8228a1646e63a3415de5/src/core/connection-status.ts#L91) and [`ConnectionLifecycle` is the enum](https://github.com/ably/ably-chat-js/blob/0ac639e8e3401400dcfe8228a1646e63a3415de5/src/core/connection-status.ts#L14).

Ahh sorry, was looking at the wrong file!

Then yes, I agree we should do the same here :)

**Comment by sacOO7** [comment]
@AndyTWF Do we need to update this as a part of the spec. I strongly feel, if spec is ambiguous, we need to update it. 
Because we are going to implement same naming conventions across SDKs

**Comment by AndyTWF** [comment]
> @AndyTWF Do we need to update this as a part of the spec. I strongly feel, if spec is ambiguous, we need to update it. Because we are going to implement same naming conventions across SDKs

The spec doesn't currently specify down to the property level what everything needs to be called - its a work in progress primarily focused on making sure we capture the intended behaviour in clear language, as well as providing testing points.

If we decide to add an IDL to the spec - then of course we'll include it.

**Comment by vladvelici** [comment]
@AndyTWF wrote [CHADR-062](https://ably.atlassian.net/wiki/spaces/CHA/pages/3410526209/CHADR-062+Renaming+Lifecycle+Types+for+Clarity) to describe the change, I've left a comment there initially but moving it here to keep the conversation in one place.

---

I think the `room.status.status` or `room.connection.status.status` syntax is not ideal, in whatever language.

The `room.status.current` next to `room.status.onChange` makes more sense to me, because it’s clear we talk about the status, it’s on a class that represents the status and nothing else. We can subscribe to changes or see the current value.

In JS, inside the implementation of the class, we actually have private variable called `_state` (could be renamed to `_status`) and provided as `current` via a getter. Can similar be done with other implementations to avoid the `room.status.status` thing?

**Comment by sacOO7** [comment]
> > @AndyTWF Do we need to update this as a part of the spec. I strongly feel, if spec is ambiguous, we need to update it. Because we are going to implement same naming conventions across SDKs
> 
> The spec for Chat doesn't currently specify down to the property level what everything needs to be called - its a work in progress primarily focused on making sure we capture the intended behaviour in clear language, as well as providing testing points for the UTS.
> 
> If we decide to add an IDL to the spec - then of course we'll include it.

I strongly feel we should have IDL for the spec. Otherwise, there will be implicit assumptions in the future that will lead to more confusion

**Comment by sacOO7** [comment]
Also, it's difficult to keep track of related discussions. I mean current discussion isn't really related to Swift and has impact across other chat SDKs

**Comment by lawrence-forooghian** [comment]
Conversation moved to https://ably.atlassian.net/wiki/spaces/CHA/pages/3410526209/CHADR-062+Renaming+Lifecycle+Types+for+Clarity

**Comment by lawrence-forooghian** [comment]
Done in #92.
